version: "3.8"

services:
  db:
    image: jagadeesh9088/employee-database-managementsystems:dbimage 
    container_name: employeedb
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: employeedb
    ports:
      - "3306:3306"

  app:
    image: jagadeesh9088/employee-database-managementsystems:appimage
    container_name: employeeapp
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always   # 🔥 IMPORTANT
